# Site settings
title: Coping with Code
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.boushley.net" # the base hostname & protocol for your site
twitter_username: boushley
github_username:  boushley
safe: true
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown
